server:
  port: 8080

spring:
  application:
    name: gitleaks-demo
  batch:
    schema: classpath:schema-h2.sql
    initialize-schema: always
    lightmin:
      batch:
        table-prefix: NOMBREPROYECTO_BATCH_
      application-name: gitleaks-demo

  resources:
    add-mappings: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:lightmin;MODE=PostgreSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 5

  datasource-bravo:
    jdbcUrl: jdbc:h2:mem:bravo;MODE=PostgreSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    maximum-pool-size: 5
    minimum-idle: 5

sanitas:
  bravocloud:
    security:
      mode: WEAK
    scheduled:
      enabled: false
      cron: "*/10 * * * * *"
    batch:
      admin:
        enabled: true

credentials:
  username: "hanauser"
  password: "c29tZXJhbmRvbXBhc3N3b3Jk"
  password_type: base64
